### ISSUE TITLE
How to compute node features

### ISSUE THREAD

**Issue by vsomnath** [fouticus/pipgcn#10]
Dear authors,

Thank you for the code! Could you point to a reference or a script on how to obtain amino acid features? Its not clear from the pkl files how to do that.

**Comment by fouticus** [comment]
Hi @vsomnath, thanks for your question. The pkl files contain the node features already. If you want to compute them yourself on a new complex, take a look at Appendix A of my MS Thesis, found [here](https://mountainscholar.org/handle/10217/185661)

Let me know if this doesn't answer your question.

**Comment by vsomnath** [comment]
Hi Alex,

Thank you for your reply! Yes, I needed to compute the features myself for newer complexes, and will have a look at your thesis.
