### ISSUE TITLE
Application to additional proteins

### ISSUE THREAD

**Issue by SSchott** [fouticus/pipgcn#13]
Hi,
Thanks for posting the code. Is there a script to get the features for a custom protein from a pdb/seq? Maybe I missed it somewhere.
Cheers,

**Comment by fouticus** [comment]
Hi @SSchott , I don't have this code right now, I'd have to contact my old adviser to get access to it again and try to clean things up a lot. It's on my list of things to do when I have more time. Sorry for the inconvenience! For now you can take a look at Appendix A of my MS thesis [here](https://mountainscholar.org/handle/10217/185661) for a description of each feature. Good luck!

**Comment by SSchott** [comment]
Thx for your reply. I will have a look at your thesis, though if you upload the code it would be helpful 😬.
