### ISSUE TITLE
about node features

### ISSUE THREAD

**Issue by XuBlack** [fouticus/pipgcn#15]
Hello, Thank you for your sharing!
I am trying to reproduce your code. However, l meet some questions about node features.
I have computed he rASA of each residue, but I don't understand how you normalize the data.
Could you describe it?
Thank you!

**Comment by fouticus** [comment]
Hi!

For more information about the feature generation, check out Appendix A of my MS thesis here: https://mountainscholar.org/bitstream/handle/10217/185661/Fout_colostate_0053N_14473.pdf?sequence=1

Feel free to respond or close the issue if you are satisfied!
