### ISSUE TITLE
Question about counting nonzero nh_indices in node_edge_average()

### ISSUE THREAD

**Issue by hsm207** [fouticus/pipgcn#2]
In line 59 of the [nn_components.py](https://github.com/fouticus/pipgcn/blob/master/nn_components.py) file, there is this line:

`   nh_sizes = tf.expand_dims(tf.count_nonzero(nh_indices + 1, axis=1, dtype=tf.float32), -1)  # for fixed number of neighbors, -1 is a pad value`

What is the purpose of counting the non-zero elements in nh_indices + 1? The number of non-zero elements in each row of nh_indices + 1 is always 20.

**Comment by fouticus** [comment]
Good question! That is a holdover from when we investigated neighborhoods of varying size, but it still works for neighborhoods of constant size.
