### ISSUE TITLE
some question about data meaning

### ISSUE THREAD

**Issue by jerrywu65** [fouticus/pipgcn#3]
In line 59 of the pw_classifier.py, there is this line:

 self.in_nhood_size = train_data[0]["l_hood_indices"].shape[1]

i know that the shape of train_data[0]["l_hood_indices"] is (185, 20, 1),but i don't know the meaning of each dimension.Could u tell me the meaning of each dimension of train_data[0]["l_hood_indices"]  ,or how to get the matrix。i want to apply  your method to my own graph.
Thx!

**Comment by fouticus** [comment]
train_data[0]["l_hood_indices"] is an array that contains the neighborhood indices for each amino acid residue (graph vertex) in the ligand of the first training example. 185 is the number of residues (vertices) in that ligand (graph). 20 is the number of neighbors (other vertices) in a convolution neighborhood. I believe 1 is a pad dimension to simplify broadcasting and tensor operations. Element (i, j, 0) in this array contains the index of the jth (spatially) closest neighboring residue (vertex) to residue (vertex) i. "Index" means along the first dimension of this array (and of the vertex features array, and one of the first two dimensions in the edge features array). 

Let me know if this doesn't make sense.

**Comment by tsjain** [comment]
I was confused by the number of residues in the pkl file compared to the PDB structures.

For example, the first training complex is 2b42. It has 184 residues in one chain. However, the training pkl file has dimension of 185 for 'l_hood_indices'. Can you explain?
