### ISSUE TITLE
have a hard time to understand the input to the GCN

### ISSUE THREAD

**Issue by wmmxk** [fouticus/pipgcn#4]
Thanks for publishing your well-organized code and the data.

I visualized the graph of the GCN (as below). Besides vertex1 and vertex2, there are other four inputs: edge1, edge2, hood_indices1 and hood_indices2. But the last four inputs are not connected to the computation graph. In the corresponding code, I saw only the first element of the [input](https://github.com/fouticus/pipgcn/blob/96e29112e1eab15c04d8e50fbfd456f2ac3a89f5/nn_components.py#L30) was used. So I was thinking about the reason why we included the edge data and hood_indices data.

In the [node_edge_average method](https://github.com/fouticus/pipgcn/blob/96e29112e1eab15c04d8e50fbfd456f2ac3a89f5/nn_components.py#L54), the edges and hood_indices are used. But this method was not used. Did I miss anything?

![model](https://user-images.githubusercontent.com/10648437/59970713-124d6700-9522-11e9-9153-b01601fce666.png)

**Comment by fouticus** [comment]
In the [run_experiments.sh](https://github.com/fouticus/pipgcn/blob/96e29112e1eab15c04d8e50fbfd456f2ac3a89f5/run_experiments.sh#L8) script, only the "no convolution" experiment is uncommented. This method doesn't use any of the edge or neighbor information. Uncommenting the other lines will perform the convolution based experiments which do use edges and neighborhoods, using, e.g. the node_edge_average method. Let me know if this is unclear.
