### ISSUE TITLE
What does the pipgcn really learn?

### ISSUE THREAD

**Issue by liyigerry** [fouticus/pipgcn#5]
For the case of node average (Equation 1), the features of center node i and its neighbor nodes were used to learn a map at each node in the graph which has the form z_i by activating a non-linear function. 

For each input pairwise ligand and receptor protein with different number of residues, the node-averaged graphs with different number of nodes will be got. What does the pipgcn really learn? What is the role of the activation function?

By the way how to handle the graphs with different nodes, or protein with different residues?

Looking forward to your explanation. Thanks.

**Comment by fouticus** [comment]
> What does the pipgcn really learn?

This is a good question which is difficult to answer precisely. The short answer is that the network learns a representation for pairs of amino acid residues such that the representations of interfacing pairs are all separable from the representations of non-interfacing pairs. It's more difficult to determine what precise features of the residues are being used (and in what manner) to create the representation. One thing we looked at was what parts of a single protein generated high activations for a particular convolutional filter. This provided insight into what a given filter was learning (See [Figure 3](https://papers.nips.cc/paper/7231-protein-interface-prediction-using-graph-convolutional-networks.pdf)). Admittedly, this only explains so much.


> What is the role of the activation function?

The activation function allows the network to learn a nonlinear decision boundary between the representations of interfacing pairs and that of non interfacing pairs.


> By the way how to handle the graphs with different nodes, or protein with different residues?

In our data set, different proteins have different numbers of residues (i.e. graphs with different numbers of nodes), and we are able to convolve their graphs for two reasons:

1. Our convolutions operate on local neighborhoods and don't require knowledge of the entire graph to work.
2. Our prediction problem involves pairs of individual residues. In other words, we are classifying (pairs of ) nodes, not entire graphs. This means we don't have to aggregate across the whole graph.

Hope this helps!
