### ISSUE TITLE
What does each node feature represents?

### ISSUE THREAD

**Issue by shionhonda** [fouticus/pipgcn#6]
Thanks for sharing your code!

The node features have 70 elements for each node, but what does each represent?
The paper describes that 20 of them are amino acid id and others are conservation score, accessible surface etc. but I can't figure out which is which.
Could you please specify the order of the node features?

**Comment by fouticus** [comment]
Hi @shionhonda , Appendix A of my MS thesis gives more details on how the node and edge features were computed and how many there are of each. The order presented in the appendix should match the order of features in the data sets. 

Here is a link to the MS thesis:
https://mountainscholar.org/handle/10217/185661

**Comment by shionhonda** [comment]
Thanks so much! It helps a lot!

**Comment by diamondspark** [comment]
@fouticus Is there any chance you might be able to provide the script for node n edge feature calculations?

**Comment by fouticus** [comment]
I'm checking with my Coauthor on sharing that code, since they wrote most of the feature generation code. This has been frequently asked for, I just haven't had much bandwidth to address it recently!
