### ISSUE TITLE
How to convert the .pdb file into the graph.

### ISSUE THREAD

**Issue by Rajratnpranesh** [fouticus/pipgcn#7]
I am looking for the script to preprocess my protein data i.e. '.pdb' file. Can you provide me with the exact file in the GitHub repo for the process?
Thank you for your help.

**Comment by fouticus** [comment]
Hi @Rajratnpranesh, 

Thanks for the question. The code to preprocess the protein data is complex and involved several third party software programs, so we opted to exclude it for cleanness and instead include the postprocessed data sets themselves. So there is no code in this repo which will preprocess new .pdb files. 

However, I have documented the preprocessing steps in detail in Appendix A of my MS thesis, which can be found [here](https://mountainscholar.org/handle/10217/185661). Feel free to take a look and let me know if you have any questions about the process. Sorry for the inconvenience. 

Alex.
