### ISSUE TITLE
data processing part

### ISSUE THREAD

**Issue by DuanhaoranCC** [fouticus/pipgcn#9]
Hello,

In your data processing part, why there are only 20 neighbors in each node? I have calculated the distance between each node and all other nodes once in a graph. If it is less than 6A, it is considered that there are edges. The number of neighbors in this way may only be 12 or other numbers, but not 20. How do you deal with your 20?

**Comment by fouticus** [comment]
Hi @DuanhaoranCC,

The 6 Angstrom number is what we use to determine if two residues _from different proteins_ form part of the interface. I.e. given residue i from protein A and residue j from protein B, they form a positive example if their distance in complex is within 6 Angstroms. 

The edges in the graphs are a different matter. Within each protein (A or B), we construct a graph from each residue to each other residue (it is a complete graph), and when performing convolution on each graph (A or B), we use the 20 nearest neighbors as a receptive field. This is performed on residues _in the same protein_. 

So it's _not_ true that if two residues are within 6 Angstroms, they form an edge in the graph representation. This is conflating the two separate ideas above. Hopefully this makes the distinction clear. Please let me know if you have a follow up question. 

Thanks!

**Comment by DuanhaoranCC** [comment]
Thank you for your answer. Your answer is very useful.
